### ISSUE TITLE
why do u use R2DBC

### ISSUE THREAD

**Issue by fizz12344321** [daggerok/liquibase-r2dbc-spring-boot-starter#4]
Hi, i am reading your project and i am interested in this, but i have a question, why do you use R2DBC instead of other non blocking IO like Hibernate Reactive or others... can you tell me your purpose, the pros and cons of R2DBC, thank you so much

**Comment by daggerok** [comment]
Hello @fizz12344321 

Thanks for your question

First of all R2DBC promoted by spring team, which provides best support, most documented and has biggest java community in comparison to other frameworks and libraries

Secondly I like an idea because its very nice matching with reactive spring programming model

I will check Hibernate Reactive when I will have time
...but when I was looking into reactive RDBMS, in that time R2DBC proposed best solution

I hope I answered your question. I will close that issue, feel free to reopen it if you have any other questions
